services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-${POSTGRES_USER}}
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - "./data:/var/lib/postgresql"
  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 127.0.0.1:8080:8080
